name: Enviar notificación al subir a main

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d "Se ha subido un archivo a la rama main" ntfy.sh/devops-itla
